spring.application.name=solid-principle
#Server port
server.port=8081

#Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/solid
spring.datasource.username=root
spring.datasource.password=root

# ORM Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update